### ISSUE TITLE
JSON formatting error on show=all

### ISSUE THREAD

**Issue by jpjenk** [EarthLifeConsortium/elc_api#10]
When returning extended location and age data two objects for each occ are returned.

**Comment by jpjenk** [comment]
Fixed. By first building a data object for each occurrence as a dictionary then appending it to a list of such dictionaries, Flask jsonify is able to correctly convert it to the appropriately formatted JSON return.

**Comment by SimonGoring** [comment]
This references commit bca36112a31f4dcf6d523dfe3b4cbad792e6d3a7.
