### ISSUE TITLE
Allow the return of tabular data in addition to JSON

### ISSUE THREAD

**Issue by jpjenk** [EarthLifeConsortium/elc_api#11]

**Comment by SimonGoring** [comment]
What does this look like for calls to:
  * age
  * grid
  * occ
  * pub
  * site
  * taxon

**Comment by SimonGoring** [comment]
The plan is to make this work first for JSON.  Once this works for JSON, and we've released the API, then we can focus on tabular output.

**Comment by jpjenk** [comment]
Tabular CSV is available across all primary routes
