### ISSUE TITLE
Check age return in /occ endpoint

### ISSUE THREAD

**Issue by jpjenk** [EarthLifeConsortium/elc_api#12]
Make sure that the min and max ages returned obey the specified agescale parameter.

Make sure that specified min and max ages are adjusted for the default in each database. Current default is Ma. These should probably adjust with the agescale parameter if it is specified for consistency with the return.

**Comment by jpjenk** [comment]
Age returns are now in the correct units. Units of specified min and max age bounds now follows the agescale parameter. That is, agescale, if given, does not only affect the returned ages but also changes the units for the min and max age parameters (again, if given). The default age units remain years before present.

**Comment by SimonGoring** [comment]
This is referenced in commit bab5f728508e390b1a173c2620db3dc45a9747e8.

**Comment by jpjenk** [comment]
Now functions correctly. Commit ccea707
