### ISSUE TITLE
Site needs to return occ_id if it is passed in the call.

### ISSUE THREAD

**Issue by SimonGoring** [EarthLifeConsortium/elc_api#2]
If `occ_id` is used in the call to the `site` endpoint then an array of occurrence IDs needs to be included in each `site` returned, so that these are lined up and can be cross-referenced.

**Comment by SimonGoring** [comment]
Currently the swagger shows a response that looks like this:

```python
[
  [
    {
      "sites": {
        "lat": 0,
        "lon": 0,
        "site_id": 0,
        "site_name": "string"
      }
    }
  ]
]
```

We want it to look like this:


```python
[
  [
    {
      "sites": {
        "lat": 0,
        "lon": 0,
        "site_id": "string",
        "site_name": "string",
        "occurences": []  # This is optional, if `occ_id` is passed in.
      }
    }
  ]
]
```

**Comment by SimonGoring** [comment]
We should call `occurences` `occ_id` to keep it consistent.

**Comment by SimonGoring** [comment]
PBDB does not have `site` as a data unit.

The `site` endpint should roll up PBDB collections by shared lat/long.

This means we should be returning information about collection units as well, so people get a sense of the temporal range of the sites.

```python
[
  [
    {
      "sites": {
        "lat": 0,
        "lon": 0,
        "site_id": "string",
        "site_name": "string",
        "collections":[{
          "id":"string",
          "name":"string"
        }],
        "occurrences": []  # This is optional, if `occ_id` is passed in.
      }
    }
  ]
]
```

**Comment by jpjenk** [comment]
This has been handled differently during API development prior to release with the hybrid ``locale`` endpoint.
