### ISSUE TITLE
Add new elements to the `taxon` end point.

### ISSUE THREAD

**Issue by SimonGoring** [EarthLifeConsortium/elc_api#3]
Taxon responses will include total number of occurrences and start & end points (means adding the `age_scale` flag.

**Comment by SimonGoring** [comment]
JSON response will look like:

```javascript
{
      "taxon": "Canis dirus",
      "taxon_id": "neot:txn:5912",
      "hierarchy":  {    //(could be null)
            "includelower":true,
            "hierarchy":"XXXXX", 
            "hierarchy_format": "newick"  // What kind of hierarchy is this?
      },
      "response":{
         "includelower":true,
         "summary":  {
               {"taxon": "Canis dirus",
               "taxon_id": "neot:txn:5912",
               "age_units": "ma",
               "max_age": 1.0,
               "min_age": 0.0,
               "occs": 1546},
               {"taxon": "Canis dirus-type",
                "taxon_id": "neot:txn:5912",
                "age_units": "ma",
                "max_age": 0.5,
                "min_age": 0.4,
                "occs": 23}
            }
     // ... (if includelower is FALSE there will only be one object returned).
     }
}
```

Things to do: 
[ ] -  Check with Daisie about whether there's a standard way for referencing hierarchy types.
[ ] - Make a decision if we want to return more than one type.

**Comment by SimonGoring** [comment]
@jpjenk can you send the link to the API documentation for hierarchy.  I'll test some Neotoma taxa against it.

**Comment by SimonGoring** [comment]
`taxonid` should be an array, that can include both Neotoma and PBDB:

```javascript
"taxon_id":{"neot:txn:5912", "pbdb:txn:43456"},
```

**Comment by jpjenk** [comment]
PBDB API documentation:
https://paleobiodb.org/data1.2

**Comment by jpjenk** [comment]
Though structured differently to the prototype above, the required data is included in version 1 of the response. Locale indices are returned as a concatenated string from ``/loc`` and ``/occ`` routes.
